#@ load("@ytt:data", "data")
#@ load("helpers.lib.yml", "resources")
#@ load("@ytt:template", "template")

#@ def config_map(name, content):
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ name
  namespace: #@ data.values.namespace
data:
  index.html: #@ content
#@ end

#!~~~~~~~~~~~~~~~~~
#! ConfigMaps
#!~~~~~~~~~~~~~~~~~
#@ for app in data.values.apps:
--- #@ config_map(app.name, app.description)
--- #@ template.replace(resources(app.name, data.values.namespace))
#@ end


#!~~~~~~~~~~~~~~~~~
#! Namespace
#!~~~~~~~~~~~~~~~~~
#@ if "namespace" in data.values:
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace
#@ end
